### ISSUE TITLE
Rename normalized Markdown topics to .dita

### ISSUE THREAD

**Issue by infotexture** [dita-ot/org.dita.normalize#6]
Markdown topics are normalized and converted to DITA, but passed through with their original filenames, which creates the impression that they have not been modified.

Tools that handle files based on extension will expect Markdown, and may fail as the content is actually XML.

**Comment by jelovirt** [comment]
@infotexture What should happen if there is already a file `test.dita` and we need to change the extension on file `test.md`. Should we change the extension using e.g. `test-<counter>.dita`. The file name will not be pretty, but the code needs some sort of rule to handle duplicate output file names.

**Comment by infotexture** [comment]
Yes, makes sense to preserve any existing files of the same name to prevent data loss.

File systems like macOS do add counters like `-1` in cases like this, so that might be the simplest option.

An alternative would be to add a static suffix to indicate that the file came from Markdown, so if `test.dita` already exists, `test.md` could be output to `test-md.dita`.
